-- 003: 상품 기준 정보와 AI 사실 근거를 분리한다.
-- intake는 Dashboard > Table Editor에서 선택할 수 있도록 enum으로 관리한다.
do $$
begin
  create type public.product_intake as enum (
    '연중 상시 접수',
    '행사별 개별 접수',
    '상담 후 진행'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.product_content_type as enum (
    'fact',
    'appeal',
    'closing',
    'caution',
    'cta'
  );
exception
  when duplicate_object then null;
end $$;

create table if not exists public.products (
  id text primary key,
  icon text not null,
  name text not null,
  tagline text,
  intake public.product_intake not null,
  handle text,
  summary text,
  site text,
  proposal_url text,
  facts jsonb not null default '[]'::jsonb,
  benefits jsonb not null default '[]'::jsonb,
  -- 상품별 선택 정보: { host, packages, events, criteria }
  details jsonb not null default '{}'::jsonb,
  cautions jsonb not null default '[]'::jsonb,

  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint products_facts_array check (jsonb_typeof(facts) = 'array'),
  constraint products_benefits_array check (jsonb_typeof(benefits) = 'array'),
  constraint products_details_object check (jsonb_typeof(details) = 'object'),
  constraint products_cautions_array check (jsonb_typeof(cautions) = 'array')
);

create table if not exists public.product_proofs (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  content_type public.product_content_type not null default 'fact',
  content jsonb not null default '[]'::jsonb,
  source_url text,
  source_label text,
  verified_at date,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_proofs_content_array check (
    jsonb_typeof(content) = 'array' and jsonb_array_length(content) > 0
  ),
  unique (product_id, content_type)
);

create index if not exists products_active_order_idx
  on public.products(sort_order) where is_active;

create index if not exists product_proofs_product_order_idx
  on public.product_proofs(product_id, sort_order) where is_active;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

drop trigger if exists product_proofs_set_updated_at on public.product_proofs;
create trigger product_proofs_set_updated_at
  before update on public.product_proofs
  for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.product_proofs enable row level security;

drop policy if exists "승인 사용자는 상품 조회" on public.products;
create policy "승인 사용자는 상품 조회" on public.products
  for select to authenticated
  using (is_active and exists (
    select 1 from public.users where users.id = auth.uid() and users.status = 'approved'
  ));

drop policy if exists "승인 사용자는 상품 근거 조회" on public.product_proofs;
create policy "승인 사용자는 상품 근거 조회" on public.product_proofs
  for select to authenticated
  using (is_active and exists (
    select 1 from public.users where users.id = auth.uid() and users.status = 'approved'
  ));

-- 수정은 Dashboard/Table Editor 또는 service_role을 사용하는 관리 스크립트에서만 한다.
-- 클라이언트용 INSERT/UPDATE/DELETE 정책은 의도적으로 만들지 않는다.
