-- 005: AI 결과 복사 이력과 사용자별 최종 선택을 저장한다.
create table if not exists public.copy_selections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  generation_group_id uuid not null,
  channel text not null check (channel in ('blog', 'instagram', 'threads')),
  variant_no smallint not null check (variant_no between 1 and 2),
  product_id text,
  topic text not null default '',
  tone text not null default '',
  generated_text text not null,
  final_text text not null,
  is_final boolean not null default true,
  copied_at timestamptz not null default now()
);

create index if not exists copy_selections_user_final_idx
  on public.copy_selections(user_id, is_final, copied_at desc);

create index if not exists copy_selections_group_channel_idx
  on public.copy_selections(user_id, generation_group_id, channel, copied_at desc);

alter table public.copy_selections enable row level security;

drop policy if exists "본인 복사 이력 조회" on public.copy_selections;
create policy "본인 복사 이력 조회" on public.copy_selections
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "본인 복사 이력 추가" on public.copy_selections;
create policy "본인 복사 이력 추가" on public.copy_selections
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "본인 복사 이력 수정" on public.copy_selections;
create policy "본인 복사 이력 수정" on public.copy_selections
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 한 트랜잭션 안에서 이전 선택을 해제하고 새 복사 행을 최종 선택으로 만든다.
create or replace function public.record_copy_selection(
  p_generation_group_id uuid,
  p_channel text,
  p_variant_no smallint,
  p_product_id text,
  p_topic text,
  p_tone text,
  p_generated_text text,
  p_final_text text
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  new_id bigint;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  update public.copy_selections
     set is_final = false
   where user_id = auth.uid()
     and generation_group_id = p_generation_group_id
     and channel = p_channel
     and is_final = true;

  insert into public.copy_selections (
    user_id, generation_group_id, channel, variant_no, product_id,
    topic, tone, generated_text, final_text, is_final
  ) values (
    auth.uid(), p_generation_group_id, p_channel, p_variant_no, p_product_id,
    coalesce(p_topic, ''), coalesce(p_tone, ''), p_generated_text, p_final_text, true
  ) returning id into new_id;

  return new_id;
end;
$$;

grant execute on function public.record_copy_selection(uuid, text, smallint, text, text, text, text, text)
  to authenticated;
