with expanded as (
  select
    pp.product_id,
    pp.id,
    pp.sort_order,
    item.value as content_item,
    item.ordinality
  from public.product_proofs pp
  cross join lateral jsonb_array_elements(pp.content)
    with ordinality as item(value, ordinality)
)
deduplicated as (
  select distinct on (product_id, content_item)
    product_id,
    content_item,
    sort_order,
    id,
    ordinality
  from expanded
  order by
    product_id,
    content_item,
    sort_order,
    id,
    ordinality
),
merged as (
  select
    product_id,
    jsonb_agg(
      content_item
      order by sort_order, id, ordinality
    ) as merged_content
  from deduplicated
  group by product_id
),
keepers as (
  select
    product_id,
    min(id) as keep_id
  from public.product_proofs
  group by product_id
)
update public.product_proofs pp
set content = m.merged_content
from merged m
join keepers k
  on k.product_id = m.product_id
where pp.id = k.keep_id;

-- 대표 행을 제외한 같은 product_id의 나머지 행 삭제

with keepers as (
  select
    product_id,
    min(id) as keep_id
  from public.product_proofs
  group by product_id
)
delete from public.product_proofs pp
using keepers k
where pp.product_id = k.product_id
  and pp.id <> k.keep_id;

drop policy if exists "승인 사용자는 상품 근거 조회"
  on public.product_proofs;


-- is_active를 사용하는 기존 partial index 제거
drop index if exists public.product_proofs_product_order_idx;


-- 기존 product_id + content_type UNIQUE 제약 제거
alter table public.product_proofs
  drop constraint if exists product_proofs_product_id_content_type_key;

alter table public.product_proofs
  drop column if exists content_type,
  drop column if exists source_url,
  drop column if exists source_label,
  drop column if exists verified_at,
  drop column if exists is_active,
  drop column if exists sort_order;

alter table public.product_proofs
  add constraint product_proofs_product_id_key
  unique (product_id);

create policy "승인 사용자는 상품 근거 조회"
  on public.product_proofs
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.users
      where users.id = auth.uid()
        and users.status = 'approved'
    )
  );

drop type if exists public.product_content_type;

create table if not exists public.product_sources (

  id bigint generated by default as identity primary key,

  product_id text not null
    references public.products(id)
    on delete cascade,

  source_url text not null,

  source_content jsonb not null default '[]'::jsonb,

  created_at timestamptz not null default now(),

  constraint product_sources_content_array check (
    jsonb_typeof(source_content) = 'array'
    and jsonb_array_length(source_content) > 0
  ),
  
  constraint product_sources_product_url_key
    unique (product_id, source_url)

);

create index if not exists product_sources_product_idx
  on public.product_sources(product_id);

  alter table public.product_sources
  enable row level security;


drop policy if exists "승인 사용자는 상품 출처 조회"
  on public.product_sources;

create policy "승인 사용자는 상품 출처 조회"
  on public.product_sources
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.users
      where users.id = auth.uid()
        and users.status = 'approved'
    )
  );