-- 009: 개인 스타일 메모리 챗봇 — 대화 로그 + 롤링 요약
--
-- 원문 대화를 매번 통째로 생성 프롬프트에 넣으면 8-18(CLAUDE.md)이 겪은
-- "프롬프트가 길어질수록 규칙 준수에 여력을 뺏겨 글이 나빠진다" 문제가 그대로 재발한다.
-- 그래서 원문은 이력(copy_chat_messages)으로만 보관하고, 생성 프롬프트에는
-- 짧게 다시 쓴 요약 한 행(user_writing_memory)만 넣는다.
--
-- 팀 공용이 아니라 **개인 전용**이다 (PLAN_V2.md 의 팀 메모리와 별개 — 2026-08-26 요청자 결정).

create table if not exists public.copy_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists copy_chat_messages_user_idx
  on public.copy_chat_messages(user_id, created_at);

alter table public.copy_chat_messages enable row level security;

drop policy if exists "본인 스타일 대화 조회" on public.copy_chat_messages;
create policy "본인 스타일 대화 조회" on public.copy_chat_messages
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "본인 스타일 대화 추가" on public.copy_chat_messages;
create policy "본인 스타일 대화 추가" on public.copy_chat_messages
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "본인 스타일 대화 삭제" on public.copy_chat_messages;
create policy "본인 스타일 대화 삭제" on public.copy_chat_messages
  for delete to authenticated using (auth.uid() = user_id);

-- 롤링 요약 — 사용자당 한 행. 매 대화 뒤 다시 써서 덮어쓴다.
create table if not exists public.user_writing_memory (
  user_id uuid primary key references auth.users(id) on delete cascade,
  summary text not null default '',
  message_count integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.user_writing_memory enable row level security;

drop policy if exists "본인 스타일 메모리 조회" on public.user_writing_memory;
create policy "본인 스타일 메모리 조회" on public.user_writing_memory
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists "본인 스타일 메모리 기록" on public.user_writing_memory;
create policy "본인 스타일 메모리 기록" on public.user_writing_memory
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "본인 스타일 메모리 수정" on public.user_writing_memory;
create policy "본인 스타일 메모리 수정" on public.user_writing_memory
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "본인 스타일 메모리 삭제" on public.user_writing_memory;
create policy "본인 스타일 메모리 삭제" on public.user_writing_memory
  for delete to authenticated using (auth.uid() = user_id);
