-- 015: AI 생성 중 "확인된 상품 사실에 없다"고 판단된 내용을 담당자가 나중에 확인할 수 있도록 기록한다.
--
-- 배경: AI가 상품 자료에 없는 내용을 정직하게 "~은 확인된 상품 사실에 포함되어 있지 않습니다"라고
-- 쓰면, 그 문장이 그대로 게시글 본문에 섞여 나갔다(요청자 제보 2026-09-02). 이제 그런 문장을
-- 발견하면 AI 생성을 멈추고 사용자에게 데이터를 보완하거나 취소할지 묻는다(app/text/page.jsx,
-- lib/missingdata.js).
--
-- 사용자가 입력한 보완 데이터는 이번 생성 1회에만 쓰이고 products/product_proofs에 자동으로
-- 반영되지 않는다(요청자 결정 2026-09-02) — 사실성 원칙(CLAUDE.md 4절)이 요구하는 공식
-- 제안서·브로셔 검증을 건너뛰지 않기 위해서다. 대신 여기에 기록해 두고, 담당자가 검토한 뒤
-- 필요하면 공식 자료로 반영한다.

create table if not exists public.missing_data_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text references public.products(id) on delete set null,
  topic text not null default '',
  channel_id text,
  stage text,
  subject text not null default '',
  sentence text not null default '',
  user_input text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists missing_data_reports_product_idx
  on public.missing_data_reports(product_id, created_at desc);

create index if not exists missing_data_reports_resolved_idx
  on public.missing_data_reports(resolved, created_at desc);

alter table public.missing_data_reports enable row level security;

drop policy if exists "본인 보완 요청 기록" on public.missing_data_reports;
create policy "본인 보완 요청 기록" on public.missing_data_reports
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "본인 보완 요청 조회" on public.missing_data_reports;
create policy "본인 보완 요청 조회" on public.missing_data_reports
  for select to authenticated using (auth.uid() = user_id);

-- 관리자는 누가 올렸든 전체를 검토하고 처리 여부(resolved)를 표시할 수 있다.
drop policy if exists "관리자는 전체 보완 요청 조회" on public.missing_data_reports;
create policy "관리자는 전체 보완 요청 조회" on public.missing_data_reports
  for select to authenticated
  using (exists (
    select 1 from public.users
    where users.id = auth.uid() and users.status = 'approved' and users.role = 'admin'
  ));

drop policy if exists "관리자는 보완 요청 처리 표시" on public.missing_data_reports;
create policy "관리자는 보완 요청 처리 표시" on public.missing_data_reports
  for update to authenticated
  using (exists (
    select 1 from public.users
    where users.id = auth.uid() and users.status = 'approved' and users.role = 'admin'
  ))
  with check (exists (
    select 1 from public.users
    where users.id = auth.uid() and users.status = 'approved' and users.role = 'admin'
  ));

comment on table public.missing_data_reports is
  'AI 생성 중 상품 자료에 없다고 판단되어 사용자가 데이터 보완을 요청받은 항목의 기록 — 담당자 검토용.';
