-- 016: AI가 생성한 글을 사용자가 문단 단위로 수정한 이력을 저장한다.
--
-- copy_selections는 복사/최종 선택된 "전체 원고"를 저장하는 용도이므로 그대로 두고,
-- 이 테이블에는 수정 이벤트를 append-only 방식으로 한 행씩 쌓는다.
-- original_text: AI가 처음 생성한 문단
-- before_text: 이번 수정 직전 문단 (재수정 시 직전 edited_text)
-- after_text: 사용자가 수정한 뒤의 문단
-- changes: 프론트엔드가 계산한 diff 등 선택 정보

create table if not exists public.copy_paragraph_edits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id text not null,
  generation_group_id uuid,
  channel text not null check (channel in ('blog', 'instagram', 'threads')),
  channel_variant text not null default '',
  product_id text references public.products(id) on delete set null,
  paragraph_index integer not null check (paragraph_index >= 0),
  paragraph_key text not null default '',
  original_text text not null,
  before_text text not null,
  after_text text not null,
  changes jsonb not null default '[]'::jsonb
    check (jsonb_typeof(changes) = 'array'),
  created_at timestamptz not null default now(),
  check (before_text is distinct from after_text)
);

comment on table public.copy_paragraph_edits is
  '블로그, 인스타그램, 쓰레드 AI 원고의 문단별 사용자 수정 이력';
comment on column public.copy_paragraph_edits.original_text is
  '해당 문단이 AI로 처음 생성됐을 때의 원문';
comment on column public.copy_paragraph_edits.before_text is
  '이번 수정 이벤트가 발생하기 직전의 문단';
comment on column public.copy_paragraph_edits.after_text is
  '이번 수정 이벤트에서 사용자가 변경한 문단';
comment on column public.copy_paragraph_edits.changes is
  '선택적 diff 목록. 예: [{"type":"replace","from":"기존","to":"변경"}]';

create index if not exists copy_paragraph_edits_user_created_idx
  on public.copy_paragraph_edits(user_id, created_at desc);

create index if not exists copy_paragraph_edits_post_channel_idx
  on public.copy_paragraph_edits(user_id, post_id, channel, paragraph_index, created_at);

create index if not exists copy_paragraph_edits_generation_idx
  on public.copy_paragraph_edits(user_id, generation_group_id, channel, created_at)
  where generation_group_id is not null;

alter table public.copy_paragraph_edits enable row level security;

drop policy if exists "본인 문단 수정 이력 조회" on public.copy_paragraph_edits;
create policy "본인 문단 수정 이력 조회" on public.copy_paragraph_edits
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "본인 문단 수정 이력 추가" on public.copy_paragraph_edits;
create policy "본인 문단 수정 이력 추가" on public.copy_paragraph_edits
  for insert to authenticated
  with check (auth.uid() = user_id);

-- user_id를 클라이언트에서 받지 않고 현재 로그인 사용자로 고정해 기록한다.
create or replace function public.record_copy_paragraph_edit(
  p_post_id text,
  p_generation_group_id uuid,
  p_channel text,
  p_channel_variant text,
  p_product_id text,
  p_paragraph_index integer,
  p_paragraph_key text,
  p_original_text text,
  p_before_text text,
  p_after_text text,
  p_changes jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  new_id bigint;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  insert into public.copy_paragraph_edits (
    user_id,
    post_id,
    generation_group_id,
    channel,
    channel_variant,
    product_id,
    paragraph_index,
    paragraph_key,
    original_text,
    before_text,
    after_text,
    changes
  ) values (
    auth.uid(),
    p_post_id,
    p_generation_group_id,
    p_channel,
    coalesce(p_channel_variant, ''),
    p_product_id,
    p_paragraph_index,
    coalesce(p_paragraph_key, ''),
    p_original_text,
    p_before_text,
    p_after_text,
    coalesce(p_changes, '[]'::jsonb)
  ) returning id into new_id;

  return new_id;
end;
$$;

revoke all on function public.record_copy_paragraph_edit(
  text, uuid, text, text, text, integer, text, text, text, text, jsonb
) from public;

grant execute on function public.record_copy_paragraph_edit(
  text, uuid, text, text, text, integer, text, text, text, text, jsonb
) to authenticated;
